# Stage 1: Builder stage
FROM gradle:jdk26-alpine AS builder

WORKDIR /build

# Ensure /lib64 exists across all architectures (amd64/arm64)
RUN mkdir -p /lib64

COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY src src

RUN gradle shadowJar --no-daemon

# Detect required Java modules from the fat JAR
RUN jdeps \
    --ignore-missing-deps \
    --print-module-deps \
    --multi-release 26 \
    /build/build/libs/*.jar 2>/dev/null \
    | tr ',' '\n' | sort -u | tr '\n' ',' | sed 's/,$//' \
    > /tmp/jdeps_modules.txt \
    && cat /tmp/jdeps_modules.txt

# Build a minimal custom JRE with jlink
# Extra modules: jdeps may miss these for Ktor CIO + Kotlin coroutines + TLS
RUN JDEPS_MODS=$(cat /tmp/jdeps_modules.txt) \
    && EXTRA_MODS="java.logging,java.naming,jdk.crypto.ec,jdk.crypto.cryptoki,jdk.unsupported,jdk.zipfs" \
    && ALL_MODS=$(printf '%s\n' $(echo "${JDEPS_MODS},${EXTRA_MODS}" | tr ',' '\n') | sort -u | tr '\n' ',' | sed 's/,$//') \
    && echo "Building JRE with modules: ${ALL_MODS}" \
    && jlink \
        --add-modules "${ALL_MODS}" \
        --strip-debug \
        --no-man-pages \
        --no-header-files \
        --compress=zip-6 \
        --output /opt/jre-minimal

# Stage 2: Runtime stage
FROM ghcr.io/cafe-horizon/horiz-os:latest

# Copy minimal C runtime libraries required by the JVM
COPY --from=builder /lib /lib
COPY --from=builder /lib64 /lib64

# Copy only essential shared libraries (instead of all 126MB of /usr/lib)
COPY --from=builder /usr/lib/libstdc++* /usr/lib/
COPY --from=builder /usr/lib/libgcc_s* /usr/lib/
COPY --from=builder /usr/lib/libz.so* /usr/lib/

# Copy the minimal JRE generated by jlink (replaces full JDK copy)
COPY --from=builder /opt/jre-minimal /opt/java/openjdk

ENV JAVA_HOME=/opt/java/openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"

WORKDIR /app

COPY --from=builder /build/build/libs/*.jar /app/app.jar

USER horiz
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
